version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/hanghae99_team3 # 인스턴스에서 파일이 저장될 위치
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu


hooks:
#  AfterInstall:
#    - location: scripts/deploy.sh
#      timeout: 60
#      runas: ubuntu
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 120
      runas: ubuntu
    - location: scripts/health_check.sh
      timeout: 120
      runas: ubuntu
    - location: scripts/switch.sh
      timeout: 120
      runas: ubuntu
